name: Code formatting & tests

on: pull_request

jobs:
  check_formatting:
    name: Check formatting ☑️
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -e '.[dev]'

      - name: Run Black
        run: |
          source venv/bin/activate
          black --check .

      - name: Run isort
        run: |
          source venv/bin/activate
          isort --check-only .

  run_tests:
    name: Run tests 🧪
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -e '.[dev]'

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --junitxml=report.xml

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.xml
